project:
  type: website
  render:
    - "*.qmd"
    - "!datasets/"
    - "!assignments/"
    - "!apps/"
    - "!notes/"
  resources:
    - "assets/"
    - "datasets/"
    - "assignments/"
    - "apps/bin/"

website:
  title: "DSC 385"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
        
    right:
      - text: "Slides"
        menu:
          - text: "Module 1: Introduction"
            href: slides/introduction.qmd
          - text: "Module 1: Aesthetic mappings"
            href: slides/aesthetic-mappings.qmd
          - text: "Module 2: Visualizing amounts"
            href: slides/visualizing-amounts.qmd
          - text: "Module 2: Telling a story"
            href: slides/telling-a-story.qmd
          - text: "Module 2: Coordinate systems and axes"
            href: slides/coordinate-systems-axes.qmd
          - text: "Module 3: Visualizing distributions 1"
            href: slides/visualizing-distributions-1.qmd
          - text: "Module 3: Visualizing distributions 2"
            href: slides/visualizing-distributions-2.qmd
          - text: "Module 4: Color scales"
            href: slides/color-scales.qmd
          - text: "Module 4: Color spaces and color-vision deficiency"
            href: slides/color-spaces.qmd
          - text: "Module 5: Data wrangling 1"
            href: slides/data-wrangling-1.qmd
          - text: "Module 5: Data wrangling 2"
            href: slides/data-wrangling-2.qmd
          - text: "Module 5: Visualizing proportions"
            href: slides/visualizing-proportions.qmd
          - text: "Module 6: Getting to know your data"
            href: slides/know-your-data.qmd
          - text: "Module 6: Getting things into the right order"
            href: slides/getting-things-in-order.qmd
          - text: "Module 7: Figure design"
            href: slides/figure-design.qmd
          - text: "Module 7: Compound figures"
            href: slides/compound-figures.qmd
          - text: "Module 8: Visualizing trends"
            href: slides/visualizing-trends.qmd
          - text: "Module 8: Functions and functional programming"
            href: slides/functional-programming.qmd
          - text: "Module 9: Working with models"
            href: slides/working-with-models.qmd
          - text: "Module 9: Visualizing uncertainty"
            href: slides/visualizing-uncertainty.qmd
          - text: "Module 10: Dimension reduction 1"
            href: slides/dimension-reduction-1.qmd
          - text: "Module 10: Dimension reduction 2"
            href: slides/dimension-reduction-2.qmd
          - text: "Module 11: Clustering"
            href: slides/clustering.qmd
          - text: "Module 11: Hierarchical clustering"
            href: slides/hierarchical-clustering.qmd 
          - text: "Module 12: Redundant coding"
            href: slides/redundant-coding.qmd 
          - text: "Module 12: Dealing with overplotting"
            href: slides/overplotting.qmd 
          - text: "Module 13: Visualizing geospatial data"
            href: slides/geospatial-data.qmd
          - text: "Module 13: Interactive plots"
            href: slides/interactive-plots.qmd
          - text: "Module 13: Animations"
            href: slides/animations.qmd
          - text: "Module 13: Web design"
            href: slides/web-design.qmd
       
      - text: "Worksheets"
        menu:
          - text: "Module 1: Introduction to Quarto"
            href: worksheets/intro-to-Quarto.qmd
          - text: "Module 1: Introduction to R"
            href: worksheets/intro-to-R.qmd
          - text: "Module 1: Aesthetic mappings"
            href: worksheets/aesthetic-mappings.qmd
          - text: "Module 2: Visualizing amounts"
            href: worksheets/visualizing-amounts.qmd
          - text: "Module 2: Coordinate systems and axes"
            href: worksheets/coordinate-systems-axes.qmd
          - text: "Module 3: Visualizing distributions 1"
            href: worksheets/visualizing-distributions-1.qmd
          - text: "Module 3: Visualizing distributions 2"
            href: worksheets/visualizing-distributions-2.qmd
          - text: "Module 4: Color scales"
            href: worksheets/color-scales.qmd
          - text: "Module 4: Color selection"
            href: worksheets/color-selection.qmd
          - text: "Module 5: Data wrangling 1"
            href: worksheets/data-wrangling-1.qmd
          - text: "Module 5: Data wrangling 2"
            href: worksheets/data-wrangling-2.qmd
          - text: "Module 5: Visualizing proportions"
            href: worksheets/visualizing-proportions.qmd
          - text: "Module 6: Getting to know your data 1"
            href: worksheets/know-your-data-1.qmd
          - text: "Module 6: Getting to know your data 2"
            href: worksheets/know-your-data-2.qmd
          - text: "Module 6: Getting things into the right order"
            href: worksheets/getting-things-in-order.qmd
          - text: "Module 7: Figure design"
            href: worksheets/figure-design.qmd
          - text: "Module 7: Compound figures"
            href: worksheets/compound-figures.qmd
          - text: "Module 8: Visualizing trends"
            href: worksheets/visualizing-trends.qmd
          - text: "Module 8: Functions and functional programming"
            href: worksheets/functional-programming.qmd
          - text: "Module 9: Working with models"
            href: worksheets/working-with-models.qmd
          - text: "Module 9: Visualizing uncertainty"
            href: worksheets/visualizing-uncertainty.qmd
          - text: "Module 10: Dimension reduction 1"
            href: worksheets/dimension-reduction-1.qmd
          - text: "Module 10: Dimension reduction 2"
            href: worksheets/dimension-reduction-2.qmd
          - text: "Module 11: Clustering"
            href: worksheets/clustering.qmd
          - text: "Module 11: Hierarchical clustering"
            href: worksheets/hierarchical-clustering.qmd 
          - text: "Module 12: Redundant coding"
            href: worksheets/redundant-coding.qmd 
          - text: "Module 12: Dealing with overplotting"
            href: worksheets/overplotting.qmd 
          - text: "Module 13: Visualizing geospatial data"
            href: worksheets/geospatial-data.qmd
          - text: "Module 13: Interactive plots"
            href: worksheets/interactive-plots.qmd
          - text: "Module 13: Web design"
            href: slides/web-design-worksheet.qmd
        

      - text: "Resources"
        menu:
        - text: "Textbook"
          href: "https://clauswilke.com/dataviz"
          target: "_blank"
        - text: "Color chooser app"
          href: apps/bin/choose-color/index.html
          target: "_blank"
        - text: "CVD simulations"
          href: apps/bin/cvd-emulator/index.html
        
    tools:
      - icon: github
        href: "https://github.com/wilkelab/DSC385"

format:
  html:
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true
  live-html:
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true
execute: 
  freeze: auto


