---
title: Disability and Access Accommodations
format: html
---

Some students receive special course accommodations from Disability and Access. Below is a list of common accommodation requests and my explanation of how I usually handle them. If you have any questions regarding any of these accommodations and/or have additional requests, please reach out to the course email address.

## Classroom Accommodations

- **Use of technology to take notes during class.** Because the course is fully remote, this accommodation does not apply.

- **Use of technology to audio record during class.** Because the course is fully remote, this accommodation does not apply.

- **A copy of class notes from a volunteer.** Because the course is fully remote, this accommodation does not apply.

- **Access to materials shown in class.** Because the course is fully remote, this accommodation does not apply.

- **Flexibility with deadlines.** The amount of flexibility we can provide is strongly constrained by the class structure, which involves peer grading. We cannot accept submissions after an assignment has been released for peer grading and solutions have been made available. This will typically happen 1-2 days after the original deadline. If you need a (short) deadline extension please reach out to the course email as early as possible (ideally before the deadline has passed) and ask for a specific amount of time you would like to have added to the deadline. (Example: "Could I have a deadline extension of one day?") Mention in your message that you have an approved accommodation for flexibility with deadlines. You do not need to explain _why_ you need the extension. 

    Please note that deadline extensions should be occasional, one-off events. We will not approve a blanket deadline extension for all assingments throughout the semester. We also encourage you to manage your deadlines proactively. Materials for homework assignments will be posted one week before the deadline, and materials for projects will be posted two weeks before the deadline. This should give you plenty of time to complete your assignments early and not push things to the last minute.

- **Flexibility with attendance.** Because the course is fully remote, this accommodation does not apply.


## Testing accommodations

This class does not have any timed exams or tests and therefore testing accommodations do not apply.
