---
title: "DSC 385 Schedule"
format: html
---

## Modules

### 1. Introduction, Aesthetic mappings

<p class="nospace">Part I:</p>

- [Slides](slides/introduction.qmd) (Introduction)
- [Worksheet 1](worksheets/intro-to-Quarto.qmd) (Introduction to Quarto)
- [Worksheet 2](worksheets/intro-to-R.qmd) (Introduction to R)

<p class="nospace">Part II:</p>

- [Slides](slides/aesthetic-mappings.qmd) (Aesthetic mappings)
- [Worksheet](worksheets/aesthetic-mappings.qmd) (Aesthetic mappings)

### 2. Visualizing amounts, Story telling, Coordinate systems

<p class="nospace">Part I:</p>

- [Slides](slides/visualizing-amounts.qmd) (Visualizing amounts)
- [Worksheet](worksheets/visualizing-amounts.qmd) (Visualizing amounts)

<p class="nospace">Part II:</p>

- [Slides](slides/telling-a-story.qmd) (Telling a story)

<p class="nospace">Part III:</p>

- [Slides](slides/coordinate-systems-axes.qmd) (Coordinate systems)
- [Worksheet](worksheets/coordinate-systems-axes.qmd) (Coordinate systems)

### 3. Visualizing distributions

<p class="nospace">Part I:</p>

- [Slides](slides/visualizing-distributions-1.qmd) (Visualizing distributions 1)
- [Worksheet](worksheets/visualizing-distributions-1.qmd) (Visualizing distributions 1)

<p class="nospace">Part II:</p>

- [Slides](slides/visualizing-distributions-2.qmd)  (Visualizing distributions 2)
- [Worksheet](worksheets/visualizing-distributions-2.qmd) (Visualizing distributions 2)

### 4. Color

<p class="nospace">Part I:</p>

- [Slides](slides/color-scales.qmd) (Color scales)
- [Worksheet](worksheets/color-scales.qmd) (Color scales)

<p class="nospace">Part II:</p>

- [Slides](slides/color-spaces.qmd) (Color spaces and color-vision deficiency)
- [Worksheet](worksheets/color-selection.qmd) (Color spaces and color-vision deficiency)

### 5. Data wrangling, Visualizing proportions

<p class="nospace">Part I:</p>

- [Slides](slides/data-wrangling-1.qmd) (Pipe, sorting, filtering, mutating)
- [Worksheet](worksheets/data-wrangling-1.qmd) (Pipe, sorting, filtering, mutating)

<p class="nospace">Part II:</p>

- [Slides](slides/data-wrangling-2.qmd) (Summarizing, pivoting, joining)
- [Worksheet](worksheets/data-wrangling-2.qmd) (Summarizing, pivoting, joining)

<p class="nospace">Part III:</p>

- [Slides](slides/visualizing-proportions.qmd) (Visualizing proportions)
- [Worksheet](worksheets/visualizing-proportions.qmd) (Visualizing proportions)

### 6. Getting to know your data, Ordering plot elemens

<p class="nospace">Part I:</p>

- [Slides](slides/know-your-data.qmd) (Getting to know your data)
- [Worksheet 1](worksheets/know-your-data-1.qmd) (Data cleaning)
- [Worksheet 2](worksheets/know-your-data-2.qmd) (Missing data)

<p class="nospace">Part II:</p>

- [Slides](slides/getting-things-in-order.qmd) (Ordering plot elemens)
- [Worksheet](worksheets/getting-things-in-order.qmd) (Ordering plot elemens)

### 7. Figure design, Compound figures

<p class="nospace">Part I:</p>

- [Slides](slides/figure-design.qmd) (Figure design)
- [Worksheet](worksheets/figure-design.qmd) (Figure design)

<p class="nospace">Part II:</p>

- [Slides](slides/compound-figures.qmd) (Compound figures)
- [Worksheet](worksheets/compound-figures.qmd) (Compound figures)

### 8. Visualizing trends, Functional programming

<p class="nospace">Part I:</p>

- [Slides](slides/visualizing-trends.qmd) (Visualizing trends)
- [Worksheet](worksheets/visualizing-trends.qmd) (Visualizing trends)

<p class="nospace">Part II:</p>

- [Slides](slides/functional-programming.qmd) (Functional programming)
- [Worksheet](worksheets/functional-programming.qmd) (Functional programming)

### 9. Working with models, Visualizing uncertainty

<p class="nospace">Part I:</p>

- [Slides](slides/working-with-models.qmd) (Working with models) 
- [Worksheet](worksheets/working-with-models.qmd) (Working with models) 

<p class="nospace">Part II:</p>

- [Slides](slides/visualizing-uncertainty.qmd) (Visualizing uncertainty)
- [Worksheet](worksheets/visualizing-uncertainty.qmd) (Visualizing uncertainty)

### 10. Dimension reduction

<p class="nospace">Part I:</p>

- [Slides](slides/dimension-reduction-1.qmd) (PCA)
- [Worksheet](worksheets/dimension-reduction-1.qmd) (PCA)

<p class="nospace">Part II:</p>

- [Slides](slides/dimension-reduction-2.qmd) (Nonlinear dimension reduction)
- [Worksheet](worksheets/dimension-reduction-2.qmd) (Nonlinear dimension reduction)

### 11. Clustering

<p class="nospace">Part I:</p>

- [Slides](slides/clustering.qmd) (Clustering)
- [Worksheet](worksheets/clustering.qmd) (Clustering)

<p class="nospace">Part II:</p>

- [Slides](slides/hierarchical-clustering.qmd) (Hierarchical clustering)  
- [Worksheet](worksheets/hierarchical-clustering.qmd) (Hierarchical clustering)

### 12. Redundant coding, text annotations, overplotting

<p class="nospace">Part I:</p>

- [Slides](slides/redundant-coding.qmd) (Redundant coding)
- [Worksheet](worksheets/redundant-coding.qmd) (Redundant coding)

<p class="nospace">Part II:</p>

- [Slides](slides/overplotting.qmd) (Overplotting)
- [Worksheet](worksheets/overplotting.qmd) (Overplotting)

### 13. Visualizing geospatial data, Miscellaneous

<p class="nospace">Part I:</p>

- [Slides](slides/geospatial-data.qmd) (Geospatial data)
- [Worksheet](worksheets/geospatial-data.qmd) (Geospatial data)

<p class="nospace">Part II:</p>

- [Slides](slides/interactive-plots.qmd) (Interactive plots)
- [Worksheet](worksheets/interactive-plots.qmd) (Interactive plots)

<p class="nospace">Part III:</p>

- [Slides](slides/animations.qmd) (Animations)

<p class="nospace">Part IV:</p>

- [Slides](slides/web-design.qmd) (Web design)
- [Worksheet](slides/web-design-worksheet.qmd) (Web design)
