---
title: "Color selection"
author: "Claus O. Wilke"
format: live-html
engine: knitr
webr:
  render-df: gt-interactive
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Introduction

In this worksheet, you will practice choosing your own colors.

First we need to load the required R packages. Please wait a moment until the live R session is fully set up and all packages are loaded.

```{webr}
#| warning: false
#| edit: false
library(tidyverse)
library(palmerpenguins)
```

Next we set up the data.

```{webr}
#| edit: false
#| warning: false
temperatures <- read_csv("https://wilkelab.org/DSC385/datasets/tempnormals.csv") |>
  mutate(
    location = factor(
      location, levels = c("Death Valley", "Houston", "San Diego", "Chicago")
    )
  ) |>
  select(location, day_of_year, month, temperature)

temps_months <- read_csv("https://wilkelab.org/DSC385/datasets/tempnormals.csv") |>
  group_by(location, month_name) |>
  summarize(mean = mean(temperature)) |>
  mutate(
    month = factor(
      month_name,
      levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
    ),
    location = factor(
      location, levels = c("Death Valley", "Houston", "San Diego", "Chicago")
    )
  ) |>
  select(-month_name)
```

We will be working with two datasets that we have seen previously. First, the `penguins` dataset:
```r
penguins
```

::: {.column-page}
```{webr}
#| echo: false
penguins
```
:::

Second, the `temps_months` dataset which contains the mean temperature for each month in four different locations.
```{webr}
#| edit: false
temps_months
```

We will start with a scatter plot of the `penguins` dataset.

```{webr}
#| label: penguins-base
#| edit: false
ggplot(penguins, aes(body_mass_g, bill_length_mm, color = species)) +
  geom_point(size = 2, na.rm = TRUE)
```

Use the <a href="../choose-color/" target="_blank">color chooser app</a> to manually pick three colors that are appropriate for a qualitative color scale. Then modify the plot to use this scale.

```{webr} 
#| exercise: penguins

```

::: { .hint exercise="penguins" }
::: { .callout-tip title="Hint" collapse="false"}
```r
ggplot(penguins, aes(body_mass_g, bill_length_mm, color = species)) +
  geom_point(size = 2, na.rm = TRUE) +
  scale_color_manual(
    values = ___ # your colors here 
  )
```
:::
:::

::: { .solution exercise="penguins" }
::: { .callout-tip title="Solution" collapse="false"}
```r
ggplot(penguins, aes(body_mass_g, bill_length_mm, color = species)) +
  geom_point(size = 2, na.rm = TRUE) +
  scale_color_manual(
    # this is just an example, there are many possible choices here
    values = c('#BF8A21', '#A74C48', '#17517A')
  )
```
:::
:::

Now let's consider this heat map of temperatures in different locations throughout the year.

```{webr}
#| label: temps-base
#| edit: false
#| fig-height: 3
ggplot(temps_months, aes(x = month, y = location, fill = mean)) + 
  geom_tile() + 
  coord_fixed(expand = FALSE)
```

Use the <a href="../choose-color/" target="_blank">color chooser app</a> to manually pick four to six colors that are appropriate for a sequential color scale. Then modify the plot to use this scale. (To create a manual color gradient, use `scale_fill_gradientn()`.)

```{webr} 
#| exercise: temps

```

::: { .hint exercise="temps" }
::: { .callout-tip title="Hint" collapse="false"}
```r
ggplot(temps_months, aes(x = month, y = location, fill = mean)) + 
  geom_tile() + 
  coord_fixed(expand = FALSE) +
  scale_fill_gradientn(
    colours = ___ # your colors here 
  )
```
:::
:::

::: { .solution exercise="temps" }
::: { .callout-tip title="Solution" collapse="false"}
```r
ggplot(temps_months, aes(x = month, y = location, fill = mean)) + 
  geom_tile() + 
  coord_fixed(expand = FALSE) +
  scale_fill_gradientn(
    # this is just an example, there are many possible choices here
    colours = c('#475010', '#8B9B38', '#C6D77C', '#F4F9E1')
  )
```
:::
:::
